### PR TITLE
build: Mark 0.4.0.post0 to align tag & pkg version

### PR DESCRIPTION
**Pull request by maybe-sybr**
You'd need to make a tag after merging this, but that's what I'm talking about doing in #20

### CODE REVIEW

**Comment by maybe-sybr** [comment]
@youngquan Any chance of getting this and some of my other PRs merged?

**Comment by youngquan** [comment]
> @youngquan Any chance of getting this and some of my other PRs merged?

sorry, i am busy recently. I will try to do it this week.

**Comment by maybe-sybr** [comment]
No problem at all, thanks for the reply :)

**Comment by youngquan** [comment]
> You'd need to make a tag after merging this, but that's what I'm talking about doing in #20
I'm sorry for the late reply.  But I'm not sure what to do. Should I push this package to pypi.org ?

**Pull request merged**
